// viewer-svelte/src/lib/components/SegmentCard.svelte
<script lang="ts">
  import type { Segment, SegmentSource } from '$lib/types';

  let {
    segment,
    editMode = false,
    onEdit,
    onDelete
  }: {
    segment: Segment;
    editMode?: boolean;
    onEdit?: () => void;
    onDelete?: () => void;
  } = $props();

  // Get segment title based on type
  function getSegmentTitle(segment: Segment): string {
    switch (segment.type) {
      case 'FLIGHT':
        return `${segment.origin.code || segment.origin.name} → ${segment.destination.code || segment.destination.name}`;
      case 'HOTEL':
        return segment.property.name;
      case 'ACTIVITY':
        return segment.name;
      case 'TRANSFER':
        return `${segment.pickupLocation.name} → ${segment.dropoffLocation.name}`;
      case 'CUSTOM':
        return segment.title;
      default:
        return 'Unknown';
    }
  }

  // Get segment subtitle
  function getSegmentSubtitle(segment: Segment): string {
    switch (segment.type) {
      case 'FLIGHT':
        return `${segment.airline.name} ${segment.flightNumber}`;
      case 'HOTEL':
        return segment.location.city || segment.location.name || '';
      case 'ACTIVITY':
        return segment.location.city || segment.location.name || '';
      case 'TRANSFER':
        return segment.transferType;
      default:
        return '';
    }
  }

  // Format time only (for day-grouped view)
  function formatTime(dateTime: string): string {
    const date = new Date(dateTime);
    return date.toLocaleString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
    });
  }

  // Get emoji icon for segment type
  function getSegmentIcon(type: string): string {
    switch (type) {
      case 'FLIGHT': return '✈️';
      case 'HOTEL': return '🏨';
      case 'ACTIVITY': return '🎯';
      case 'TRANSFER': return '🚗';
      case 'CUSTOM': return '📝';
      default: return '📌';
    }
  }

  // Get source label and icon
  function getSourceLabel(source: SegmentSource): { icon: string; text: string } {
    switch (source) {
      case 'import':
        return { icon: '📄', text: 'Imported' };
      case 'agent':
        return { icon: '🤖', text: 'Auto-generated' };
      case 'manual':
        return { icon: '✏️', text: 'User added' };
      default:
        return { icon: '📌', text: source };
    }
  }

  // Get border color for source (using inline style for reliability)
  function getSourceBorderColor(source: SegmentSource): string {
    switch (source) {
      case 'import':
        return '#60a5fa'; // blue-400
      case 'agent':
        return '#c084fc'; // purple-400
      case 'manual':
        return '#4ade80'; // green-400
      default:
        return '#d1d5db'; // gray-300
    }
  }
</script>

<div class="minimal-card p-4 space-y-2 border-l-4" style="border-left-color: {getSourceBorderColor(segment.source)}">
  <!-- Title with icon and edit controls -->
  <div class="flex items-start gap-3">
    <span class="text-2xl">{getSegmentIcon(segment.type)}</span>
    <div class="flex-1 min-w-0">
      <h4 class="font-medium text-minimal-text">
        {getSegmentTitle(segment)}
      </h4>
      {#if getSegmentSubtitle(segment)}
        <p class="text-sm text-minimal-text-muted mt-0.5">
          {getSegmentSubtitle(segment)}
        </p>
      {/if}
    </div>
    {#if editMode}
      <div class="flex gap-1">
        {#if onEdit}
          <button
            class="edit-icon-button"
            onclick={onEdit}
            type="button"
            title="Edit segment"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path>
              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path>
            </svg>
          </button>
        {/if}
        {#if onDelete}
          <button
            class="delete-icon-button"
            onclick={onDelete}
            type="button"
            title="Delete segment"
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="3 6 5 6 21 6"></polyline>
              <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
            </svg>
          </button>
        {/if}
      </div>
    {/if}
  </div>

  <!-- Time and Source -->
  <div class="flex items-center gap-2 text-sm text-minimal-text-muted ml-11">
    <span>{formatTime(segment.startDatetime)}</span>
    <span class="text-gray-300">·</span>
    <span class="inline-flex items-center gap-1 text-xs">
      <span>{getSourceLabel(segment.source).icon}</span>
      <span>{getSourceLabel(segment.source).text}</span>
    </span>
  </div>

  <!-- Source details (for agent-generated segments) -->
  {#if segment.source === 'agent' && segment.sourceDetails}
    <div class="text-xs text-minimal-text-muted ml-11 flex items-center gap-2">
      {#if segment.sourceDetails.model}
        <span class="inline-flex items-center gap-1">
          <span class="font-mono">{segment.sourceDetails.model}</span>
        </span>
      {/if}
      {#if segment.sourceDetails.confidence}
        <span>·</span>
        <span>Confidence: {Math.round(segment.sourceDetails.confidence * 100)}%</span>
      {/if}
    </div>
  {/if}

  <!-- Notes -->
  {#if segment.notes}
    <p class="text-xs text-minimal-text-muted italic ml-11">
      {segment.notes}
    </p>
  {/if}

  <!-- Inferred indicator -->
  {#if segment.inferred}
    <div class="text-xs text-minimal-accent ml-11">
      Inferred: {segment.inferredReason || 'gap filling'}
    </div>
  {/if}
</div>

<style>
  .edit-icon-button,
  .delete-icon-button {
    background: none;
    border: none;
    cursor: pointer;
    padding: 0.25rem;
    border-radius: 0.25rem;
    color: #6b7280;
    transition: all 0.2s;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .edit-icon-button:hover {
    background-color: #f3f4f6;
    color: #3b82f6;
  }

  .delete-icon-button:hover {
    background-color: #fef2f2;
    color: #dc2626;
  }
</style>

// viewer/src/components/SegmentCard.tsx
import { Plane, Hotel, MapPin, Car, Activity, FileText } from 'lucide-react';
import type { Segment } from '../types';

interface SegmentCardProps {
  segment: Segment;
}

const SEGMENT_COLORS = {
  FLIGHT: 'bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800',
  HOTEL: 'bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800',
  TRANSFER: 'bg-orange-50 dark:bg-orange-900/20 border-orange-200 dark:border-orange-800',
  ACTIVITY: 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800',
  MEETING: 'bg-indigo-50 dark:bg-indigo-900/20 border-indigo-200 dark:border-indigo-800',
  CUSTOM: 'bg-gray-50 dark:bg-gray-900/20 border-gray-200 dark:border-gray-800',
};

const SEGMENT_ICONS = {
  FLIGHT: Plane,
  HOTEL: Hotel,
  TRANSFER: Car,
  ACTIVITY: Activity,
  MEETING: MapPin,
  CUSTOM: FileText,
};

function getSegmentTitle(segment: Segment): string {
  switch (segment.type) {
    case 'FLIGHT':
      return `${segment.origin.code} → ${segment.destination.code}`;
    case 'HOTEL':
      return segment.property.name;
    case 'ACTIVITY':
      return segment.name;
    case 'TRANSFER':
      return `${segment.pickupLocation.name} → ${segment.dropoffLocation.name}`;
    case 'CUSTOM':
      return segment.title;
    default:
      return 'Unknown';
  }
}

function getSegmentDetails(segment: Segment): string[] {
  const details: string[] = [];

  switch (segment.type) {
    case 'FLIGHT':
      details.push(`${segment.airline.name} ${segment.flightNumber}`);
      if (segment.cabin) details.push(segment.cabin);
      break;
    case 'HOTEL':
      if (segment.roomType) details.push(segment.roomType);
      if (segment.location.city) details.push(segment.location.city);
      break;
    case 'ACTIVITY':
      if (segment.location.city) details.push(segment.location.city);
      break;
    case 'TRANSFER':
      details.push(segment.transferType);
      break;
  }

  return details;
}

function formatDateTime(dateTime: string): string {
  const date = new Date(dateTime);
  return date.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

function getSourceBadge(source: string): { icon: string; label: string; color: string } {
  switch (source) {
    case 'import':
      return { icon: '📄', label: 'Import', color: 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200' };
    case 'agent':
      return { icon: '🤖', label: 'Agent', color: 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200' };
    case 'manual':
      return { icon: '✍️', label: 'Manual', color: 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' };
    default:
      return { icon: '❓', label: 'Unknown', color: 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200' };
  }
}

export function SegmentCard({ segment }: SegmentCardProps) {
  const Icon = SEGMENT_ICONS[segment.type];
  const colorClass = SEGMENT_COLORS[segment.type];
  const title = getSegmentTitle(segment);
  const details = getSegmentDetails(segment);
  const sourceBadge = getSourceBadge(segment.source);

  return (
    <div className={`p-4 border rounded-lg ${colorClass}`}>
      <div className="flex items-start justify-between gap-2 mb-2">
        <div className="flex items-start gap-3 flex-1">
          <Icon className="w-5 h-5 mt-0.5 flex-shrink-0" />
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold text-gray-900 dark:text-gray-100 truncate">
              {title}
            </h3>
            {details.length > 0 && (
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-0.5">
                {details.join(' • ')}
              </p>
            )}
          </div>
        </div>
        <span className={`px-2 py-1 text-xs font-medium rounded-full flex-shrink-0 ${sourceBadge.color}`}>
          {sourceBadge.icon} {sourceBadge.label}
        </span>
      </div>

      <div className="text-sm text-gray-700 dark:text-gray-300 space-y-1">
        <div>
          <span className="font-medium">Start:</span> {formatDateTime(segment.startDatetime)}
        </div>
        <div>
          <span className="font-medium">End:</span> {formatDateTime(segment.endDatetime)}
        </div>
      </div>

      {segment.notes && (
        <p className="mt-2 text-sm text-gray-600 dark:text-gray-400 italic">
          {segment.notes}
        </p>
      )}

      {segment.inferred && segment.inferredReason && (
        <div className="mt-2 p-2 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded text-xs">
          <span className="font-medium text-yellow-800 dark:text-yellow-200">Inferred:</span>{' '}
          <span className="text-yellow-700 dark:text-yellow-300">{segment.inferredReason}</span>
        </div>
      )}

      <div className="mt-2 flex items-center gap-2">
        <span className={`
          px-2 py-0.5 text-xs font-medium rounded
          ${segment.status === 'CONFIRMED' ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200' : ''}
          ${segment.status === 'TENTATIVE' ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200' : ''}
          ${segment.status === 'CANCELLED' ? 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200' : ''}
        `}>
          {segment.status}
        </span>
        <span className="px-2 py-0.5 text-xs font-medium rounded bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200">
          {segment.type}
        </span>
      </div>
    </div>
  );
}
